baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hyde"
title = "A pé ou de carro"
[params]
  description = "Chega-se a qualquer lado"

disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""

